<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Cours;
use UserBundle\Entity\User;


/**
 * AvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAnimateur(User $user){

        $qb = $this->createQueryBuilder("a")
            ->leftJoin('AppBundle:Cours', 'co', 'WITH', 'co.id = a.cours')
            ->where(':animateurs MEMBER OF co.animateurs')
            ->setParameters(array('animateurs' => $user));

        return $qb->getQuery()->getResult();

    }

    public function findAvisByCoursAndDanseur(User $user, Cours $cours)
    {
        $qb = $this->createQueryBuilder("a")
            ->andWhere('a.cours = :cours AND a.danseur = :danseur')
            ->setParameters(array('danseur' => $user,
                                    'cours' => $cours));

        return $qb->getQuery()->getOneOrNullResult();
    }

}
