<?php

namespace AppBundle\Repository;

/**
 * CourantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourantRepository extends \Doctrine\ORM\EntityRepository
{
}
