app_admin_courants_new:
    path: /new
    defaults: { _controller: "AppBundle:Admin/Courant:new"}

app_admin_courants_edit:
    path: /{id}/edit
    defaults: { _controller: "AppBundle:Admin/Courant:edit"}

app_admin_courants_delete:
    path: /{id}/delete
    defaults: { _controller: "AppBundle:Admin/Courant:delete"}