app_admin_evenements_index:
    path: /
    defaults: { _controller: "AppBundle:Admin/Evenement:index"}

app_admin_evenements_new:
    path: /new
    defaults: { _controller: "AppBundle:Admin/Evenement:new"}

app_admin_evenements_edit:
    path: /{id}/edit
    defaults: { _controller: "AppBundle:Admin/Evenement:edit"}

app_admin_evenements_delete:
    path: /{id}/delete
    defaults: { _controller: "AppBundle:Admin/Evenement:delete"}