app_admin_niveaux_index:
    path: /
    defaults: { _controller: "AppBundle:Admin/Niveau:index"}

app_admin_niveaux_new:
    path: /new
    defaults: { _controller: "AppBundle:Admin/Niveau:new"}

app_admin_niveaux_edit:
    path: /{id}/edit
    defaults: { _controller: "AppBundle:Admin/Niveau:edit"}

app_admin_niveaux_delete:
    path: /{id}/delete
    defaults: { _controller: "AppBundle:Admin/Niveau:delete"}