app_admin_salles_index:
    path: /
    defaults: { _controller: "AppBundle:Admin/Salle:index"}

app_admin_salles_new:
    path: /new
    defaults: { _controller: "AppBundle:Admin/Salle:new"}

app_admin_salles_edit:
    path: /{id}/edit
    defaults: { _controller: "AppBundle:Admin/Salle:edit"}

app_admin_salles_delete:
    path: /{id}/delete
    defaults: { _controller: "AppBundle:Admin/Salle:delete"}