app_admin_users_index:
    path: /
    defaults: { _controller: "AppBundle:Admin/User:index"}

app_admin_users_new:
    path: /new
    defaults: { _controller: "AppBundle:Admin/User:new"}

app_admin_users_edit:
    path: /{id}/edit
    defaults: { _controller: "AppBundle:Admin/User:edit"}

app_admin_users_edit_password:
    path: /{id}/editpassword
    defaults: { _controller: "AppBundle:Admin/User:editPassword"}