AppBundle\Entity\Salle:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SalleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomSalle:
            type: string
            length: 255
            column: nom_salle
        numeroSalle:
            type: integer
            column: numero_salle
        capaciteSalle:
            type: integer
            column: capacite_salle
    lifecycleCallbacks: {  }
